refactor: Radio 컴포넌트 확장성있게 변경
price-offer/offer-design-system pull request #185
Opened 2023-08-28 07:50 UTC by shinhyojeong

## 🔗 이슈 번호

- closed #184 

## ⛳ 구현 사항
* Radio 컴포넌트 확장성있게 변경

## 📚 구현 설명
* 라디오 컴포넌트의 리스트를 children으로 받아 아이템 형태를 자유롭게 구현할 수 있도록 수정합니다.

## ⏳ 실행 화면
### Default
<img width="285" alt="스크린샷 2023-08-28 오후 4 49 42" src="https://github.com/price-offer/offer-design-system/assets/70738281/cc8da72e-3c89-44d6-9b84-22561f302ca4">

### children
<img width="221" alt="스크린샷 2023-08-28 오후 4 50 07" src="https://github.com/price-offer/offer-design-system/assets/70738281/d820ba07-cae0-4ab9-9c9d-5520649b7ccf">

2023-09-28 08:50 UTC, sonsurim requested changes

2023-09-28 08:50 UTC, sonsurim commented on packages/react/src/components/Radio/Default.tsx
> +  }: RadioProps,
타입으로 children과 items가 공존하지 못하게 막는 건 어떠신가요??

현재 items가 있어도 children만 허용되는데 인터페이스에 혼란을 줄 수 있어 방지하는 것도 좋을 것 같습니다

2023-09-28 13:40 UTC, chojooyoung reviewed
저는 이견없습니다!! 제가 너무 확장성을 고려안하고 짯었네요 ㅠㅠㅎㅎ 
효정님 감사합니다!!

2023-09-29 16:46 UTC, shinhyojeong commented on packages/react/src/components/Radio/Default.tsx
> +  }: RadioProps,
두가지가 공존하는 것이 어색하다는 의견에 동의합니다 !

고민해봤는데 어떤 방식으로 처리해야할지 몰라서 수림님의 구체적인 의견이 듣고싶습니다.
제가 처리하려는 방식은 아래와 같은데 가딩이 잘 이루어지지 않는 상황입니다. 다른 방법이 있을까유? 🤔
``` 
type CommonProps = {
  formName: string
  direction: 'horizontal' | 'vertical'
  onChange(e: ChangeEvent<HTMLFormElement>): void
}
type DefaultProps = CommonRadioProps & { items: any }
type ChildrenProps = CommonRadioProps & { children: ReactNode }

export type RadioProps = DefaultRadioProps | ChildrenRadioProps
```

2023-10-01 17:18 UTC, sonsurim commented on packages/react/src/components/Radio/Default.tsx
> +  }: RadioProps,
@shinhyojeong 효정님과 인식 동일합니당 ㅎㅎ

```ts
type DefaultProps = CommonProps & { items: any; children?: never }
type ChildrenProps = CommonProps & { items?: never; children: any }
```
never 넣어주면 가딩될 것 같아요!

2023-10-02 13:22 UTC, shinhyojeong commented on packages/react/src/components/Radio/Default.tsx
> +  }: RadioProps,
앗 never를 추가해주면 되는군여 👍

[반영](https://github.com/price-offer/offer-design-system/pull/185/commits/545d34b0e0c85df58f63bd14bb35eb139edefa90) 완료 !

2023-10-03 08:32 UTC, sonsurim approved these changes
LGTM 👍

2023-10-03 13:52 UTC, merged